global:
  scrape_interval: 15s

scrape_configs:
  # Scrape our FastAPI app — /metrics endpoint
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['10.0.1.177:80']

  # Scrape system metrics from EC2
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.1.177:9100']